version: "3.7"

services:
  web:
    build: ./nginx/
    image: liliangaladima/web-app-web:1.5
    container_name: nginx-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./www/html/:/var/www/html/

  php:
    build: ./php/
    image: liliangaladima/web-app-php:1.5
    container_name: php-container
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./www/html/:/var/www/html/

  mysql:
    build: ./mysql/
    image: liliangaladima/web-app-mysql:1.5
    container_name: mysql-container
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
